Bump the minor-updates group with 2 updates (#300)
Bumps the minor-updates group with 2 updates:
[rails](https://github.com/rails/rails) and
[clearance](https://github.com/thoughtbot/clearance).

Updates `rails` from 7.1.3.4 to 7.2.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">rails's
releases</a>.</em></p>
<blockquote>
<h2>7.2.0</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Fix <code>delegate_missing_to allow_nil: true</code> when called with
implict self</p>
<pre lang="ruby"><code>class Person
  delegate_missing_to :address, allow_nil: true
<p>def address<br />
nil<br />
end</p>
<p>def berliner?<br />
city == &quot;Berlin&quot;<br />
end<br />
end</p>
<p>Person.new.city # =&gt; nil<br />
Person.new.berliner? # undefined local variable or method `city' for an
instance of Person (NameError)<br />
</code></pre></p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Add <code>logger</code> as a dependency since it is a bundled gem
candidate for Ruby 3.5</p>
<p><em>Earlopain</em></p>
</li>
<li>
<p>Define <code>Digest::UUID.nil_uuid</code>, which returns the
so-called nil UUID.</p>
<p><em>Xavier Noria</em></p>
</li>
<li>
<p>Support <code>duration</code> type in
<code>ActiveSupport::XmlMini</code>.</p>
<p><em>heka1024</em></p>
</li>
<li>
<p>Remove deprecated
<code>ActiveSupport::Notifications::Event#children</code> and
<code>ActiveSupport::Notifications::Event#parent_of?</code>.</p>
<p><em>Rafael Mendonça França</em></p>
</li>
<li>
<p>Remove deprecated support to call the following methods without
passing a deprecator:</p>
<ul>
<li><code>deprecate</code></li>
<li><code>deprecate_constant</code></li>

<li><code>ActiveSupport::Deprecation::DeprecatedObjectProxy.new</code></li>

<li><code>ActiveSupport::Deprecation::DeprecatedInstanceVariableProxy.new</code></li>

<li><code>ActiveSupport::Deprecation::DeprecatedConstantProxy.new</code></li>
<li><code>assert_deprecated</code></li>
<li><code>assert_not_deprecated</code></li>
</ul>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/fb6c4305939da06efdf2893d99130e7829c53e8b"><code>fb6c430</code></a>
Preparing for 7.2.0 release</li>
<li><a
href="https://github.com/rails/rails/commit/c9a5cfdb751edfc06d66c9ab21b48d2e5a0d662a"><code>c9a5cfd</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52540">#52540</a>
from mattbrictson/fix-brakeman-ci-desc</li>
<li><a
href="https://github.com/rails/rails/commit/ac2035adc0b5211fc84ddddaec7c656f761b8659"><code>ac2035a</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52555">#52555</a>
from rails/rm-fix-system-test</li>
<li><a
href="https://github.com/rails/rails/commit/7ae1ec1aecaf17b9a13aa4138f80189e251092a1"><code>7ae1ec1</code></a>
Remove WEB_CONCURRENCY &quot;auto&quot; from
tuning_performance_for_deployment (<a
href="https://redirect.github.com/rails/rails/issues/52545">#52545</a>)</li>
<li><a
href="https://github.com/rails/rails/commit/0461267eda2e8fdaff131f460134fb924d43d84b"><code>0461267</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52554">#52554</a>
from erados/patch-1</li>
<li><a
href="https://github.com/rails/rails/commit/c2e0f6fb55b390472db7253e3ff722514f9f76f9"><code>c2e0f6f</code></a>
Remove redundant Puma configuration settings from fresh config/puma.rb
files</li>
<li><a
href="https://github.com/rails/rails/commit/ecf787c9f75d49428424687b8b971bb6da11a17c"><code>ecf787c</code></a>
Puma 5+ now pulls WEB_CONCURRENCY directly from ENV, so we cannot/should
not ...</li>
<li><a
href="https://github.com/rails/rails/commit/573d4bd4604b8f760a0e0b6c3695d4affd126063"><code>573d4bd</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52533">#52533</a>
from denys-chaikovskyi/mod/auto-puma-workers</li>
<li><a
href="https://github.com/rails/rails/commit/0b3404edae56dcf5935d9692a06236fd2284ec95"><code>0b3404e</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52531">#52531</a>
from n-studio/allow-bots</li>
<li><a
href="https://github.com/rails/rails/commit/6ffa94cac1a0fcfac94403678835263e62a35ef1"><code>6ffa94c</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52524">#52524</a>
from rubys/rm-redundant-comment</li>
<li>Additional commits viewable in <a
href="https://github.com/rails/rails/compare/v7.1.3.4...v7.2.0">compare
view</a></li>
</ul>
</details>
<br />

Updates `clearance` from 2.7.2 to 2.8.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/thoughtbot/clearance/releases">clearance's
releases</a>.</em></p>
<blockquote>
<h2>v2.8.0</h2>
<p><a
href="https://github.com/thoughtbot/clearance/compare/v2.7.2...v2.8.0">2.8.0</a>
- August 9, 2024</p>
<h1>Added</h1>
<ul>
<li>Feature: Added allow_password_resets config option (<a
href="https://redirect.github.com/thoughtbot/clearance/issues/1019">#1019</a>)</li>
<li>Added dependabot (<a
href="https://redirect.github.com/thoughtbot/clearance/issues/1028">#1028</a>)</li>
<li>Added a dynamic workflow to update SECURITY.md to match thoughtbot's
security template (5a5a625680dee28925882270252979233c220df2)</li>
</ul>
<h1>Fixed</h1>
<ul>
<li>Fixed some deprecation warnings (<a
href="https://redirect.github.com/thoughtbot/clearance/issues/1018">#1018</a>)</li>
</ul>
<p>Thanks so much to our community contributors Jos O'shea (<a
href="https://github.com/whatnotery"><code>@​whatnotery</code></a>) and
Karine Vieira (<a
href="https://github.com/karinevieira"><code>@​karinevieira</code></a>)!
🎉</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/thoughtbot/clearance/blob/main/CHANGELOG.md">clearance's
changelog</a>.</em></p>
<blockquote>
<h2><a
href="https://github.com/thoughtbot/clearance/compare/v2.7.2...v2.8.0">2.8.0</a>
- August 9, 2024</h2>
<ul>
<li>Feature: Added allow_password_resets config option (<a
href="https://redirect.github.com/thoughtbot/clearance/issues/1019">#1019</a>)
Jos O'shea</li>
<li>Added dependabot (<a
href="https://redirect.github.com/thoughtbot/clearance/issues/1028">#1028</a>)
Karine Vieira</li>
<li>Fixed some deprecation warnings (<a
href="https://redirect.github.com/thoughtbot/clearance/issues/1018">#1018</a>)</li>
<li>Added a dynamic workflow to update SECURITY.md</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/thoughtbot/clearance/commit/90f1029a27f6b0ce15da22be479978ddd321abd2"><code>90f1029</code></a>
Release 2.8.0</li>
<li><a
href="https://github.com/thoughtbot/clearance/commit/dbfe55dcf465b6f15e825353cdfaf8b1f81720c2"><code>dbfe55d</code></a>
Add allow_password_resets config option (<a
href="https://redirect.github.com/thoughtbot/clearance/issues/1019">#1019</a>)</li>
<li><a
href="https://github.com/thoughtbot/clearance/commit/87bca53c2adb0812764f32935a4bac81a67d8f2c"><code>87bca53</code></a>
Fix test deprecation warnings (<a
href="https://redirect.github.com/thoughtbot/clearance/issues/1018">#1018</a>)</li>
<li><a
href="https://github.com/thoughtbot/clearance/commit/0398217e1b29d75bb42aa5219dbd5eba7c1cb310"><code>0398217</code></a>
Add dependabot action (<a
href="https://redirect.github.com/thoughtbot/clearance/issues/1028">#1028</a>)</li>
<li><a
href="https://github.com/thoughtbot/clearance/commit/b88caa5ac22472fb5e9b8d14e33981be8b46256b"><code>b88caa5</code></a>
docs: documentation files updated (<a
href="https://redirect.github.com/thoughtbot/clearance/issues/1030">#1030</a>)</li>
<li><a
href="https://github.com/thoughtbot/clearance/commit/50936aa065c0c2da01c6aa9cf13bf692c38d4b68"><code>50936aa</code></a>
docs: documentation files updated (<a
href="https://redirect.github.com/thoughtbot/clearance/issues/1029">#1029</a>)</li>
<li><a
href="https://github.com/thoughtbot/clearance/commit/5a5a625680dee28925882270252979233c220df2"><code>5a5a625</code></a>
Add dynamic security workflow and update SECURITY.md</li>
<li>See full diff in <a
href="https://github.com/thoughtbot/clearance/compare/v2.7.2...v2.8.0">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>